export const locales = ['ru', 'en', 'az'];

export const copy = {
  ru: {
    nav: { home: 'Главная', services: 'Услуги', about: 'О компании', gallery: 'Галерея', faq: 'FAQ', contacts: 'Контакты' },
    heroEyebrow: 'Логистика из США без лишних звеньев',
    heroTitle: 'Ваш груз.\nНаш маршрут.',
    heroText: 'Организуем доставку автомобилей, спецтехники и водного транспорта — от поиска на аукционе до выдачи в стране назначения.',
    primaryCta: 'Получить расчет', secondaryCta: 'Смотреть услуги',
    stats: [{ value: '12+', label: 'направлений доставки' }, { value: '24/7', label: 'на связи с клиентом' }, { value: '98%', label: 'отправок в срок' }],
    servicesEyebrow: 'Что мы делаем', servicesTitle: 'Логистика, собранная вокруг вашей задачи', servicesText: 'Один партнер закрывает весь маршрут: покупка, документы, консолидация, погрузка и доставка.',
    processEyebrow: 'Прозрачный процесс', processTitle: 'От заявки до получения — под контролем',
    process: [{ no: '01', title: 'Обсуждаем задачу', text: 'Уточняем груз, маршрут, сроки и предлагаем оптимальную схему.' }, { no: '02', title: 'Готовим маршрут', text: 'Берем на себя документы, проверку и организацию отправки.' }, { no: '03', title: 'Доставляем', text: 'Фиксируем каждый этап и держим вас в курсе до получения груза.' }],
    trustEyebrow: 'Почему Northline', trustTitle: 'Спокойствие на каждом этапе международной перевозки', trustText: 'Временный текст о компании. Здесь появится история бренда, опыт команды и конкретные преимущества после передачи материалов.',
    trustPoints: ['Единый координатор проекта', 'Фотофиксация погрузки и состояния груза', 'Работа с надежными портами и перевозчиками', 'Поддержка на русском, английском и азербайджанском'],
    galleryEyebrow: 'В работе', galleryTitle: 'Маршруты, которые уже в движении', galleryCta: 'Открыть галерею',
    quoteEyebrow: 'Начнем с вашей задачи', quoteTitle: 'Получите предварительный расчет маршрута', quoteText: 'Опишите груз и направление — мы вернемся с ответом в течение рабочего дня.',
    footerText: 'Международная логистика с человеческим лицом.',
    form: { name: 'Ваше имя', contact: 'Телефон или email', cargo: 'Что нужно доставить?', route: 'Откуда и куда?', message: 'Комментарий', send: 'Отправить заявку', success: 'Спасибо! Заявка принята. Мы свяжемся с вами в ближайшее время.' },
    details: 'Подробнее', back: 'Назад к услугам', allServices: 'Все услуги', contactTitle: 'Свяжитесь с нами'
  },
  en: {
    nav: { home: 'Home', services: 'Services', about: 'About us', gallery: 'Gallery', faq: 'FAQ', contacts: 'Contact' },
    heroEyebrow: 'Logistics from the USA, without the extra steps', heroTitle: 'Your cargo.\nOur route.', heroText: 'We arrange delivery of vehicles, heavy equipment and watercraft — from auction search to handover at destination.', primaryCta: 'Get a quote', secondaryCta: 'View services',
    stats: [{ value: '12+', label: 'delivery directions' }, { value: '24/7', label: 'client support' }, { value: '98%', label: 'on-time dispatches' }], servicesEyebrow: 'What we do', servicesTitle: 'Logistics built around your brief', servicesText: 'One partner for the whole route: purchase, paperwork, consolidation, loading and delivery.', processEyebrow: 'A clear process', processTitle: 'From request to delivery — under control', process: [{ no: '01', title: 'We discuss your brief', text: 'We clarify cargo, route and timing, then propose the best solution.' }, { no: '02', title: 'We build the route', text: 'We handle documents, checks and dispatch coordination.' }, { no: '03', title: 'We deliver', text: 'We document every stage and keep you informed until handover.' }], trustEyebrow: 'Why Northline', trustTitle: 'Confidence at every stage of an international shipment', trustText: 'Placeholder company story. This section will be replaced with the brand history, team experience and verified benefits.', trustPoints: ['One project coordinator', 'Loading and cargo condition photo reports', 'Trusted ports and carrier network', 'Support in Russian, English and Azerbaijani'], galleryEyebrow: 'In motion', galleryTitle: 'Routes already on the move', galleryCta: 'Open gallery', quoteEyebrow: 'Let’s start with your brief', quoteTitle: 'Get a preliminary route estimate', quoteText: 'Tell us about your cargo and destination — we will reply within one business day.', footerText: 'International logistics with a human touch.', form: { name: 'Your name', contact: 'Phone or email', cargo: 'What needs to be delivered?', route: 'From where and to where?', message: 'Comment', send: 'Send request', success: 'Thank you! Your request has been received.' }, details: 'Learn more', back: 'Back to services', allServices: 'All services', contactTitle: 'Get in touch'
  },
  az: {
    nav: { home: 'Ana səhifə', services: 'Xidmətlər', about: 'Haqqımızda', gallery: 'Qalereya', faq: 'FAQ', contacts: 'Əlaqə' },
    heroEyebrow: 'ABŞ-dan logistika — artıq addımlar olmadan', heroTitle: 'Sizin yükünüz.\nBizim marşrutumuz.', heroText: 'Avtomobil, xüsusi texnika və su nəqliyyatının auksiondan təhvilə qədər çatdırılmasını təşkil edirik.', primaryCta: 'Qiymət alın', secondaryCta: 'Xidmətlərə bax', stats: [{ value: '12+', label: 'çatdırılma istiqaməti' }, { value: '24/7', label: 'müştəri dəstəyi' }, { value: '98%', label: 'vaxtında göndəriş' }], servicesEyebrow: 'Nə edirik', servicesTitle: 'Sizin tapşırığınıza uyğun logistika', servicesText: 'Alış, sənədlər, konsolidasiya, yükləmə və çatdırılma üçün vahid tərəfdaş.', processEyebrow: 'Aydın proses', processTitle: 'Sorğudan təhvilə qədər — nəzarətdə', process: [{ no: '01', title: 'Tapşırığı müzakirə edirik', text: 'Yükü, marşrutu və müddəti dəqiqləşdiririk.' }, { no: '02', title: 'Marşrutu hazırlayırıq', text: 'Sənədləri və göndərişin təşkilini öz üzərimizə götürürük.' }, { no: '03', title: 'Çatdırırıq', text: 'Hər mərhələni sənədləşdirir və sizi məlumatlandırırıq.' }], trustEyebrow: 'Niyə Northline', trustTitle: 'Beynəlxalq daşınmanın hər mərhələsində inam', trustText: 'Müvəqqəti şirkət mətni. Brend tarixi və komandanın təcrübəsi sonradan əlavə ediləcək.', trustPoints: ['Layihənin vahid koordinatoru', 'Yükləmə və yük vəziyyətinin foto hesabatı', 'Etibarlı liman və daşıyıcı şəbəkəsi', 'Rus, ingilis və azərbaycan dillərində dəstək'], galleryEyebrow: 'İş prosesində', galleryTitle: 'Hərəkətdə olan marşrutlar', galleryCta: 'Qalereyanı aç', quoteEyebrow: 'Tapşırığınızla başlayaq', quoteTitle: 'Marşrut üçün ilkin hesab alın', quoteText: 'Yük və istiqamət haqqında yazın — iş günü ərzində cavab verəcəyik.', footerText: 'İnsan yönümlü beynəlxalq logistika.', form: { name: 'Adınız', contact: 'Telefon və ya email', cargo: 'Nə çatdırılmalıdır?', route: 'Haradan hara?', message: 'Şərh', send: 'Sorğu göndər', success: 'Təşəkkür edirik! Sorğunuz qəbul edildi.' }, details: 'Ətraflı', back: 'Xidmətlərə qayıt', allServices: 'Bütün xidmətlər', contactTitle: 'Bizimlə əlaqə saxlayın'
  }
};

export const services = [
  { id: 'vehicles', icon: '01', title: { ru: 'Автомобили из США', en: 'Vehicles from the USA', az: 'ABŞ-dan avtomobillər' }, text: { ru: 'Подбор, проверка, покупка и доставка автомобиля под ваш бюджет.', en: 'Selection, inspection, purchase and delivery built around your budget.', az: 'Büdcənizə uyğun avtomobil seçimi, yoxlanışı və çatdırılması.' }, image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80' },
  { id: 'container', icon: '02', title: { ru: 'Контейнерные перевозки', en: 'Container shipping', az: 'Konteyner daşımaları' }, text: { ru: 'Безопасная консолидация автомобилей, техники и запчастей в одном контейнере.', en: 'Safe consolidation of vehicles, equipment and parts in one container.', az: 'Avtomobil, texnika və ehtiyat hissələrinin təhlükəsiz konsolidasiyası.' }, image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=900&q=80' },
  { id: 'roro', icon: '03', title: { ru: 'Ro-Ro доставка', en: 'Ro-Ro shipping', az: 'Ro-Ro daşımaları' }, text: { ru: 'Горизонтальная погрузка транспорта на судно с оптимальным маршрутом.', en: 'Efficient roll-on/roll-off shipping for vehicles and heavy equipment.', az: 'Nəqliyyat üçün səmərəli roll-on/roll-off daşınması.' }, image: 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=900&q=80' },
  { id: 'heavy', icon: '04', title: { ru: 'Спецтехника', en: 'Heavy equipment', az: 'Xüsusi texnika' }, text: { ru: 'Логистика крупногабаритной техники, оборудования и водного транспорта.', en: 'Logistics for oversized equipment, machinery and watercraft.', az: 'İri texnika, avadanlıq və su nəqliyyatı üçün logistika.' }, image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=900&q=80' },
  { id: 'parts', icon: '05', title: { ru: 'Запчасти и разбор', en: 'Parts & dismantling', az: 'Ehtiyat hissələri' }, text: { ru: 'Поиск деталей, разбор и подготовка автомобильных компонентов к экспорту.', en: 'Parts sourcing, dismantling and export preparation for automotive components.', az: 'Detalların axtarışı, sökülməsi və ixrac üçün hazırlanması.' }, image: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=80' },
  { id: 'air', icon: '06', title: { ru: 'Авиа-доставка', en: 'Air freight', az: 'Hava daşımaları' }, text: { ru: 'Когда важна скорость: организуем доставку срочных и ценных грузов.', en: 'When speed matters: urgent and high-value cargo delivered by air.', az: 'Sürətin vacib olduğu təcili və qiymətli yüklər üçün hava daşımaları.' }, image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80' }
];

export const gallery = [
  { category: 'vehicles', title: { ru: 'Автомобили на складе', en: 'Vehicles at the yard', az: 'Anbarda avtomobillər' }, image: 'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=80' },
  { category: 'shipping', title: { ru: 'Погрузка контейнера', en: 'Container loading', az: 'Konteyner yüklənməsi' }, image: 'https://images.unsplash.com/photo-1565610222536-ef125c59da2e?auto=format&fit=crop&w=1200&q=80' },
  { category: 'equipment', title: { ru: 'Техника в пути', en: 'Equipment in transit', az: 'Yolda texnika' }, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80' },
  { category: 'shipping', title: { ru: 'Морской маршрут', en: 'Ocean route', az: 'Dəniz marşrutu' }, image: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?auto=format&fit=crop&w=1200&q=80' }
];

export const getService = (id) => services.find((service) => service.id === id) || services[0];
